mystudent:
  # 名称
  name: hecm
  # 版本
  version: 1.0.1
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/mystudent/uploadPath
  # 获取ip地址开关
  addressEnabled: true


spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      # 模板引擎
  thymeleaf:
      mode: HTML
      encoding: utf-8

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: admin.com.student.*.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# PageHelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
